services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.FE
      args:
        - NEXT_PUBLIC_BACKEND_API_URL=${NEXT_PUBLIC_BACKEND_API_URL}
    container_name: diary_frontend
    ports:
      - "${FE_PORT}:3000"
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.BE
      args:
        - APP_NAME=${APP_NAME}
        - APP_KEY=${APP_KEY}
        - APP_DEBUG=${APP_DEBUG}
        - APP_TIMEZONE=${APP_TIMEZONE}
        - APP_URL=${APP_URL}
        - APP_LOCALE=${APP_LOCALE}
        - APP_FALLBACK_LOCALE=${APP_FALLBACK_LOCALE}
        - FRONTEND_URL=${FRONTEND_URL}
        - APP_LOCALE=${APP_LOCALE}
        - APP_FALLBACK_LOCALE=${APP_FALLBACK_LOCALE}
        - APP_FAKER_LOCALE=${APP_FAKER_LOCALE}
        - PHP_CLI_SERVER_WORKERS=${PHP_CLI_SERVER_WORKERS}
        - BCRYPT_ROUNDS=${BCRYPT_ROUNDS}
        - DB_CONNECTION=${DB_CONNECTION}
        - DATABASE_URL=${DATABASE_URL}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_DATABASE=${DB_DATABASE}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - VITE_APP_NAME=${VITE_APP_NAME}
    ports:
      - "${BE_PORT}:${BE_PORT}"
    container_name: diary_backend
    volumes:
      - ./backend:/app
    depends_on:
      - db

volumes:
  db_data:
